### ISSUE TITLE
additional Clocks showing the wrong time (TZ not checked)

### ISSUE THREAD

**Issue by tommycologne** [martinet101/ElevenClock#1006]
V 3.9.3
Normal TZ is Berlin.
Times for Sydney and Los Angeles showing same time as for Berlin.
Was working in prior Version !

**Comment by tommycologne** [comment]
Works normal, if Elevenclock is closed. It´s not a WIN 11 issue.

**Comment by martinet101** [comment]
Ill try to fix that

**Comment by andrew-flatters-bliss** [comment]
Think this is the same problem as I mentioned in my comment on [#989](https://github.com/martinet101/ElevenClock/issues/989#issuecomment-1289029540)

**Comment by martinet101** [comment]
Yes, it probably is

**Comment by albiek1976** [comment]
Hello, 

The **first version** with the **wrong time in tooltips is v. 3.9.2**
It shows the same time in both local time and the second time I use is UTC


**The last version working is v 3.9.1**
I'm comparing that with 1:56a Wed  (New York City Time) to 5:56a Wed (UTC) time. 

~~~

I uninstalled v3.93 and went backward to each install version until I found the one that worked with my
Win 11 home version

With Regards,
albiek1976

**Comment by martinet101** [comment]
Could you please try this release?
https://github.com/martinet101/ElevenClock/releases/tag/3.9.3-r2

**Comment by albiek1976** [comment]
Per your instructions.It didn't fix the issueBut, there aren't any issues with v 3.9.1
Albert V. Kollar
e-mail: ***@***.*** 

    On Thursday, November 10, 2022 at 01:39:51 PM EST, Martí Climent ***@***.***> wrote:  
 
 


Could you please try this release?
https://github.com/martinet101/ElevenClock/releases/tag/3.9.3-r2

**Comment by martinet101** [comment]
Hi,

could you please try this release (it is a new version)?

https://github.com/martinet101/ElevenClock/releases/tag/3.9.4-beta2

**Comment by albiek1976** [comment]
Hello,

With this version, The issue remains.  
The experimental FIX Win+N clock, non-Latin is checkmarked
**My Local and the UTC time in the _tooltip_ are the same time**. 
(I'm in a +5 UTC timezone).
[The picture attachment from my last e-mail is where the issue is]
I've rebooted multiple times, In settings, I reset to defaults and then changed the preferences back to my liking.

-----------------

Win + N has the correct UTC time in Windows 11 Calendar / Focus area. 


---- 

If you need any clarification let me know.

Thanks

**Comment by martinet101** [comment]
Hi,

Could you please test this release and send your log?

https://github.com/martinet101/ElevenClock/releases/tag/3.9.4-beta3

**Comment by martinet101** [comment]
Thanks!
