### ISSUE TITLE
Clock shows over fullscreen

### ISSUE THREAD

**Issue by JackMJOneill** [martinet101/ElevenClock#11]
I don't know if's normal or not but the clock is over fullscreen mode. Can you make it disapear when switching in fs ?

**Comment by martinet101** [comment]
Yes, this was what i was planning to do, because I also prefer it to show over fullscreen apps

**Comment by Xzandro** [comment]
It really is not great. Especially if you watch some kind of video or movie on fullscreen, where some controls tend to be at the bottom right. You constantly click on the clock instead of the video controls.

**Comment by martinet101** [comment]
I'll add a switch

**Comment by Kippenhof** [comment]
> It really is not great. Especially if you watch some kind of video or movie on fullscreen, where some controls tend to be at the bottom right. You constantly click on the clock instead of the video controls.

Oh, yes. That can sometimes get annoying. It would be nice if the clock isn't clickebale if it shows over Programs, that could eliminate my Problem with it.

**Comment by DumpoJerome** [comment]
Well since some people prefer it to be on during fullscreen and some don't, I would suggest just adding a switch that enables it to stay up during fullscreen, but probably keep it hidden during fullscreen by default since that is what most people will be used to from Windows 10.

I do appreciate that half-fix though, but as Xzandro said, it's quite tedious to do manually when watching Youtube where oftentimes I find myself going in and out of fullscreen very often.

**Comment by martinet101** [comment]
I've implemented a fix on that will be launched on version 1.8.

The thing is that if the clock is in a window where's a focused full-screen window it will hide. Otherwise it will show.

**Comment by martinet101** [comment]
@Xzandro It will only hide the clock on the monitor where's the fullscreen app
