### ISSUE TITLE
[FEATURE REQUEST] MSIX installer

### ISSUE THREAD

**Issue by sguergachi** [martinet101/ElevenClock#127]
I would love to be able to install this using modern MSIX installer since its easy to manage in modern Windows.

**Comment by urifoox** [comment]
I believe the developer has said that the issue is the cost of getting whatever is needed to digitally sign the code. Based on https://techcommunity.microsoft.com/t5/msix-deployment/is-there-already-a-way-to-install-unsigned-msix-packages-right/m-p/215352 it looks like MSIX wouldn't be available then. If you know more about getting code signed/costs please let us know, maybe we can collectively afford it?

**Comment by martinet101** [comment]
Yes, the issue is the actual cost, and the converted from classical insstallers to msix is hard to use and sometimes does not work (i tested it with non-signed files). Anyway, i'm investingating signing files with a self-signed certificate to be able to determine if the file is real or not.

**Comment by martinet101** [comment]
Nope, we are talking about signing certificates (I actually got in trouble also finding the difference between both of them)
