### ISSUE TITLE
[BUG] Timezone change is not reflected

### ISSUE THREAD

**Issue by franssenm** [martinet101/ElevenClock#129]
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened
## To Reproduce
-Change your timezone, ElevenClock not updated

Keep up the good work

**Comment by franssenm** [comment]
Pity you are giving up so easily. Not really the spirit of a dev. Still,
great job in general and good luck to you!

**Comment by martinet101** [comment]
Hey @franssenm , I understand it seems like I'm giving up easily, but this feature is one of the features I failed to implement from de beginning, and I had already done an exhaustive research over the internet. And when you submitted the issue, I gave it a 2nd chance, with no luck. I'm sorry it felt like I'm giving up, but this is not true. I'll still search a solution either until I find it or either until the Eleven Project dies. I may found a workaround some time after, but since this is not a high priority bug, it thought it wouldn't be as important as trying to fix the three monitor issue. Anyway, after changing a timezone, when you shut down your pc and boot it again it will reflect changes, but in this coming version, due to another bug solution after waking up from sleep it will also restart ElevenClock. I'm sorry I can't fix that now :'(, but trust me, I'll stay trying. 

P. D. I actually found a solution, but it took like 30% of cpu and I thought it wouldn't be a good idea, and also required the user to have python installed on the system. But I'll still investigate. 

(it might seem like I'm mad, but trust me I'm not ;)  
Hope you still enjoy ElevenClock after all)
