### ISSUE TITLE
Windows 11 added their own clock

### ISSUE THREAD

**Issue by axlroden** [martinet101/ElevenClock#299]
Just FYI, Windows 11 added the clock to all monitors now.

**Comment by Grenaid** [comment]
Any link?

**Comment by JohnLGalt** [comment]
I wonder if that is an Insider's build....

**Comment by JohnLGalt** [comment]
While a clock supplied by Windows would be more useful than the current situation, I seriously doubt they will include things like the seconds, or the Week number, or allowing for font sizing...

IOW - I'm not leaving 11Clock any time soon.

**Comment by axlroden** [comment]
I'm an idiot, it was another 3rd party (StartAllBack) that added it when I enabled enhanced classic taskbar .. not actually Microsoft..

**Comment by martinet101** [comment]
Ah ok, then nothing ;)

**Comment by martinet101** [comment]
Now it's official, latest insider build added secondary clock

**Comment by urifoox** [comment]
I think it was pretty clear from the start that Microsoft would add missing functionality that's been in every version of Windows for the past two decades into Windows 11. There's other things still missing like the ability to never combine icons on the taskbar and thousands of other feature requests in the Feedback Hub. 

Having said that, the work that's been done here is really impressive and the evolution from V0.1 to today is massive. I think you should be very proud of the work and the tens of thousands of people you've helped! I am sure you can leverage this type of work into other opportunities. I was and still do encourage you to reach out to Microsoft and let them know this exists...you never know where it can take you. https://www.youtube.com/channel/UCNzszbnvQeFzObW0ghk0Ckw - this guy built the original Task Manager! Reach out to him and maybe he has some contacts he can introduce you to.

If you continue to maintain this, that's awesome because it helps a lot of people and like you said it still has way more functionality than what Microsoft is offering right now. Ultimately though I do think you can leverage this to much bigger opportunities.

**Comment by martinet101** [comment]
> I think it was pretty clear from the start that Microsoft would add missing functionality that's been in every version of Windows for the past two decades into Windows 11. There's other things still missing like the ability to never combine icons on the taskbar and thousands of other feature requests in the Feedback Hub.
> 
> Having said that, the work that's been done here is really impressive and the evolution from V0.1 to today is massive. I think you should be very proud of the work and the tens of thousands of people you've helped! I am sure you can leverage this type of work into other opportunities. I was and still do encourage you to reach out to Microsoft and let them know this exists...you never know where it can take you. https://www.youtube.com/channel/UCNzszbnvQeFzObW0ghk0Ckw - this guy built the original Task Manager! Reach out to him and maybe he has some contacts he can introduce you to.
> 
> If you continue to maintain this, that's awesome because it helps a lot of people and like you said it still has way more functionality than what Microsoft is offering right now. Ultimately though I do think you can leverage your skills and talents to much bigger opportunities.

@urifoox, definely I will maintain this, because, as you said, it has far more features that default clock, and also i am learning a lot from it. Actually, i'm gonna use ElevenClock as my research project, since, as you said, it evolved a lot since 0.1 (Actually I published it as a backup for my code.) Anyway, thank you all also for your contributions, donations and the support you all have gave me. **Thank you all for making ElevenClock possible!**

**Comment by martinet101** [comment]
Btw, there's a feature suggestion to hide default system clock, if you wanted to upvote it it would be nice :)
    https://aka.ms/AAf0z56

**Comment by JohnLGalt** [comment]
Bot gonna lie - even if they add in the clock on multi-taskbars, I'm sticking with ElevenClock.

One main function is that having a second clock on the primary monitor at the left is massively beneficial - because it even shows through on full screen apps, like games.  The other is that, when the default clock populates, it should be on the right in all other monitors like the primary - and with EC set for the left, I now have clocks on both sides of the taskbar, one of which always shows. And with my taskbar now firmly cemented in the center, this works really, really well.

You've done some awesome work here, and I just swapped over from the Git-derived installer to the M$ Store installer, and it seemed to have kept my settings in place as well.
