### ISSUE TITLE
[BUG] Missing latest Czech translation

### ISSUE THREAD

**Issue by panther7** [martinet101/ElevenClock#425]
My commits with Update Czech translation missing in v2.9.2, check:
* https://github.com/martinet101/ElevenClock/compare/2.9.1...2.9.2

![2021-12-28 14 58 28](https://user-images.githubusercontent.com/3808250/147573767-07e364db-8971-4fb7-bd44-3ba0ecbf2120.png)

**Comment by martinet101** [comment]
Yes, the 2.9.2 update was launched on monday, but it was uploaded and built on the previous sunday, and it had been delayed because of issues with the github releases page (basically, it wouldn't let you download anything. ) That's why I posponed the update.

This is the latest source code:
![image](https://user-images.githubusercontent.com/53119851/147574438-f378662a-3c55-40b0-aeaa-4b63bb86e3c8.png)

**Comment by panther7** [comment]
Ok, but "Tag" v2.9.2 (https://github.com/martinet101/ElevenClock/compare/2.9.1...2.9.2) is not reflect real source code included. :-/

**Comment by martinet101** [comment]
Yep, you are actually right. Gonna mark this on the release
