### ISSUE TITLE
[BUG] (When using startallback + elevenclock time is messed up)

### ISSUE THREAD

**Issue by ananddvn04** [martinet101/ElevenClock#458]
![image](https://user-images.githubusercontent.com/91336664/148373852-c0558081-a07e-443b-b5a4-44028ccf3767.png)
  
I am using startallback a application to make taskbar smaller like windows 10...

but seconds is very very imp to me.....

so i tried using eleven clock after all issues but it is showing weirdly and occupying more space i tried decreasing font size but it so much smaller than expected and goes before taskbar which messes up more and fonts / texts are mixed up....
can someone help / what to do??

**Comment by martinet101** [comment]
Can you please decrease taskbar size as you would do with the standard windows taskbar? (tutorial here: https://www.tomshardware.com/how-to/change-taskbar-icon-size-windows-11)

**Comment by kylefmohr** [comment]
Hi, I am having the same issue due to the combination of StartAllBack and ElevenClock. I tried decreasing the taskbar size as described in the link, and after a reboot, the taskbar size appears to be unaffected (I'm guessing StartAllBack is causing that), however now ElevenClock is both shrunk and cut off on the top and bottom. Running v3.0.0 of ElevenClock 
![image](https://user-images.githubusercontent.com/6644803/148511119-7718e4c2-8116-4b7e-bdf4-8e290dca2a88.png)

**Comment by martinet101** [comment]
I cloud add some custom height adjustments. Would that help?

**Comment by kylefmohr** [comment]
In my opinion, that would help. Ideally, I'd like the option to specify the location of the box on-screen, but I don't know how practical implementing that would be.

**Comment by ananddvn04** [comment]
I mean like is there no way of integrating it directly into taskbar

**Comment by martinet101** [comment]
> I mean like is there no way of integrating it directly into taskbar

No. That's whhy ElevenClock is so buggy

**Comment by martinet101** [comment]
> I cloud add some custom height adjustments. Would that help?

I'll wait until i fix this

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/149013380-bca01f40-1101-410e-bdfa-ce92ee4d919f.png)

Comign in next version
