### ISSUE TITLE
Clicking on clock sometimes opens calendar, sometimes does not

### ISSUE THREAD

**Issue by urifoox** [martinet101/ElevenClock#7]
Click on clock sometimes on the main monitor you get

![image](https://user-images.githubusercontent.com/22828430/136049838-1c37a453-cb9a-4049-a52e-e0b56253fcf1.png)

Sometimes you get nothing and it disappears.

**Comment by martinet101** [comment]
Yes, I'm aware of that, but i can't solve it. The thing is that when you click the clock, it simulates Win+N key presses to open the calendar and notifications. Because sometimes when you press Win+N windows does not open the caendar (Yeah, it's partially broken at least on my computer), I can't do nothing else than wait and hope Microsoft fixes this.

**Comment by urifoox** [comment]
I am not able to ever replicate Win+N not working.

**Comment by urifoox** [comment]
I am not able to ever replicate the calendar not opening on the default system clock.

**Comment by martinet101** [comment]
In my computer Win+N works, but sometimes is just broken. Try restarting explorer.exe

**Comment by urifoox** [comment]
The issue is more nuanced:

1/ If you click the small space between the clock/date, it never opens
2/ If the clock disappears/reappears you have to click on it or away and then on it for the calendar to open

**Comment by martinet101** [comment]
1. I've noticed and fixed, but not released yet
2. This is what I said before, it is because of the taskbar

**Comment by urifoox** [comment]
I do not think this is a Microsoft issue, release 1.5 fixed this problem and fixed the clock disappearing.
