### ISSUE TITLE
Background size variability with numbers 1 and 2

### ISSUE THREAD

**Issue by Draskic** [martinet101/ElevenClock#719]
Hi
Maybe it would be convenient if the background of the clock is variable with the numbers 1 and 2?
Thus, for units, the background is asymmetrical, although the setting is to center the text of the clock.
Regards, Drasko

![Background variability](https://user-images.githubusercontent.com/24246539/161240287-d6bb2fc3-6748-414f-b012-477f05571dcf.jpg)

**Comment by martinet101** [comment]
Well, i'll take a look, but this might consume more cpu than expected...

**Comment by martijnvankekem** [comment]
This is probably due to the fact that you have a monospace font. This means that all characters and numbers have the exact same width. The remaining space for the one is filled with empty space to match the width of the wider numbers.

The disadvantage of removing the monospace font is that the clock will move around while ticking. Take 22:15 for example. Then the width of the clock will change each time a one changes to a two. This can cause some weird effects.

I'm not a developer or affiliated with this project, but I'd say it's better to leave it this way than to change it.

**Comment by martinet101** [comment]
> it's better to leave it this way than to change it

Yes, since the implementation would mean active monitoring of the clock's width and the actual context width, and this would mean ElevenClock consuming ~10% CPU (i have tested it)

**Comment by Draskic** [comment]
You are right!
I'm already used to it! Especially when I hear your explanation!
Best wishes and greetings!
Drasko

**Comment by Draskic** [comment]
Hi
I understand that.
In fact it’s just the finesse I noticed when I added a black background
because it’s not possible to use outlined fonts.
Greetings from Drasko

**Comment by Draskic** [comment]
I wouldn’t say I have monospace fonts. I use Windows 11 upgraded to Windows
10 and I use the same system fonts. I don’t worry about them too much!
Eleven clock uses the same system fonts, and the developer himself replied
that it was too much work and did not mention monofonts!
Hello and all the best!
Drasko
