### ISSUE TITLE
[FEATURE REQUEST] Startup impact

### ISSUE THREAD

**Issue by albiek1976** [martinet101/ElevenClock#811]
I like the program but the startup impact is **HIGH**. Would you fix the startup impact for _windows 10 & 11_ **LOW** or **NONE**?

Thanks

**Comment by martinet101** [comment]
Short answer, Not quite.

Long answer. Also no. This is because:

This impact is calculated idk how, and while Windows says it is _HIGH_, the launch time of this app is nothing more than 1~2 seconds in most cases, and without using 100% of cpu during launch. 

Additionally, this impact is partially caused by Python loading, and though much can't be done, and the other part is caused by essential parts of the app, since non-essential processes in the app are already throttled and delayed.

Best thing you can do is enabling low-cpu mode in the settings window, but this would impact the general behaviour, not the launch of the app...

**Comment by Masamune3210** [comment]
In addition, Windows claims almost everything has a high impact to startup, its not exactly a detailed measurement

**Comment by albiek1976** [comment]
Thanks for the information
