### ISSUE TITLE
Folder created 

### ISSUE THREAD

**Issue by PeteM92** [martinet101/ElevenClock#819]
since 3.6.1 a folder ist created in root folder c:. folder ist removed, when ElevenClock is closed.

**Comment by kkm000** [comment]
I confirm that the folder is created at the root of drive C:, currently _MEI157962 but it seems the name varies. The folder ACL allows access to my identity and not even SYSTEM, which is not a good practice. procexp shows that DLLs are actually loaded by elevenclock.exe. Below is the structure of the folder (only directories, no files), which you may find helpful in identifying the issue.

Another suggestion: is it possible to create the contents of the folder once, during setup/upgrade, in the program's installation directory? Unpacking the archive takes time on each logon, and the nature of the program is such that it runs in background anyway as long as the user is logged on. The unpack-on-run strategy thus does not save disk space, rather increases it: The packed archive in the main executable takes space, but could have been discarded after unpacking it once during setup. The directory size is just over 100MB, the executable size is 50MB. Not too large either way. The start-up time impact _is_ really concerning, however!

```
C:\_MEI157962
+---psutil
+---PySide2
|   +---plugins
|   |   +---bearer
|   |   +---iconengines
|   |   +---imageformats
|   |   +---platforminputcontexts
|   |   +---platforms
|   |   +---platformthemes
|   |   \---styles
|   \---translations
+---resources
+---shiboken2
+---tcl
|   +---encoding
|   +---http1.0
|   +---msgs
|   +---opt0.4
|   \---tzdata
|       +---Africa
    [... a geography lesson snipped... ]
|       +---Mexico
|       +---Pacific
|       +---SystemV
|       \---US
+---tcl8
|   +---8.4
|   |   \---platform
|   +---8.5
|   \---8.6
+---tk
|   +---images
|   +---msgs
|   \---ttk
\---win32com
    \---shell
```

**Comment by martinet101** [comment]
I know that this is not the best strategy, but PyInstaller won't let me compile in dir mode.

This folder shouldn't be created here, so can you please try creating a folder called 'elevenclock' under the %appdata% folder?

**Comment by martinet101** [comment]
I know that this is not the best strategy, but PyInstaller won't let me compile in dir mode.

This folder shouldn't be created here, so can you please try creating a folder called 'elevenclock' under the %appdata% folder?

**Comment by PeteM92** [comment]
I´d prefer no folder created. The folders which were created in %appdata% before, were not cleared.

**Comment by martinet101** [comment]
Yes, this is going to be fixed soon

**Comment by PeteM92** [comment]
Thank you, now it´s ok!

**Comment by kkm000** [comment]
Thanks for the fix! I confirm both that the folder is now created under %TEMP%, and cleaned up on program's restart via its own context menu. I didn't  confirm cleanup on log off or on restart, will keep an eye on that! BTW, I got the update automatically via the Store. I had to kill the folder in C:\ by hand after the upgrade, as expected; no other ill effects.

> PyInstaller won't let me compile in dir mode.

That's a bummer. So, essentially, the problem is that your code doesn't even get a chance to run anything before it unconditionally uncompresses the internal archive—am I understanding the issue? I've seen the bit of cleanup code that globs for `_MEI*` folders, but could not see any that would be doing the unpacking part...

Another idea: what if there were a little bootstrapper executable that checked if an unpacked directory is present, and then if yes, would launch the main program from it, and if not, run the full PyInstaller package instead to unpack and launch? To avoid a chicken-and-egg problem here, such an executable could not be written in Python tho... I'm wondering what other options are available for store packages. I've been programming for Windows in C/C++ since Windows 3.0, and could make one in a couple hours, but I'm totally unfamiliar with the store-distributed apps, what API can they use; just never had to care about that. If you're interested, I'll get myself up to speed to contribute such a workaround, when I get time. Can't commit to an ETA, but I like ElevenClock so much that I certainly want it improved!

**Comment by PeteM92** [comment]
Just an additional comment: when you make some improvements please have an additional look at some tmpxyz folders and mat-debug-1234.log files, which are created by ElevenClock in this %TEMP% folder.

**Comment by martinet101** [comment]
Hmmm, this one shouldn't be created... I haven't seen them never, but I'll take a look...

**Comment by martinet101** [comment]
> I didn't confirm cleanup on log off or on restart,

Instead of cleaning on close, the next instance will check for unised `_mei*` dirs and will erase them
