### ISSUE TITLE
 the clock is no longer in the background in full screen,

### ISSUE THREAD

**Issue by FisPet** [martinet101/ElevenClock#987]
Hello, the clock is no longer in the background in full screen, and it does not read information from the task area to the surface, attached is a screenshot
![2022-10-13 12_18_22-ElevenClock](https://user-images.githubusercontent.com/115703887/195572021-6fae0b28-16ba-4971-a5ba-78025259c53d.png)
LG Peter

**Comment by martinet101** [comment]
Yes, this is a known issue that can't be fixed, since the clock can't show under menus but over windows. 

I'm sorry but this can't be fixed.

The best thing I can say is to move the icons on the expandable flyout, so the context menus show a little bit upper. See the following example:

![image](https://user-images.githubusercontent.com/53119851/195584337-545947b4-9a88-4de7-996a-5c4109e53dab.png)
![image](https://user-images.githubusercontent.com/53119851/195584395-a5590aff-318d-46be-a6dd-256669adcb45.png)

**Comment by FisPet** [comment]
Hi ok it's a pity, but the idea of postponing it helped me too, Many Thanks BR
Peter

mit freundlichen Grüßen
Peter Fischer
53909 Zülpich
Mail: ***@***.***
Mobile: +49 15153864352


Am Do., 13. Okt. 2022 um 13:27 Uhr schrieb Martí Climent <
***@***.***>:
